#!/bin/bash

# Small script for watching a the current directory and running
# a command if anything changes.  Depends on inotify-tools.
#
# I use it like:  hawk mvn clean test

if [ "x`which inotifywait`" = "x" ]; then 
  echo "Fatal error right here:";
  echo "  The hawk needs inotify-tools to be installed."; 
  echo "  Try apt-get or yum, or whatever.";
  exit;
fi

DIR=`pwd`;
CMD=$@;

echo;
echo "Watching '$DIR' like a hawk"
echo "Will run '$CMD' if anything changes";

cd $DIR

while true;
do 
  echo;
  echo "the hawk is waiting...";
  inotifywait -q -r $DIR @$DIR/.idea -e modify -e create -e delete -e move > /dev/null;
  echo "the hawk is running $CMD";
  ( $CMD )
done
